---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "ecomm-front-end-mock"
  name: "ecomm-front-end-mock-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "ecomm-front-end-mock"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: []
        envFrom: []
        image: "rajkumar/ecomm-front-end-mock:0.1.0"
        imagePullPolicy: "IfNotPresent"
        name: "ecomm-front-end-mock-deployment"
        ports:       
        - containerPort: 8280
          name: http         
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
